-- Deutsch am Abend community schema
-- Run this in Supabase SQL Editor, then enable email confirmations in Authentication settings.

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 80),
  created_at timestamptz not null default timezone('utc', now())
);

create table public.level_memberships (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  level text not null check (level in ('A1', 'A2', 'B1', 'B2')),
  created_at timestamptz not null default timezone('utc', now())
);

create table public.posts (
  id bigint generated by default as identity primary key,
  level text not null check (level in ('A1', 'A2', 'B1', 'B2')),
  author_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 100),
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default timezone('utc', now())
);

create table public.replies (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default timezone('utc', now())
);

create table public.post_reactions (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  reaction text not null check (reaction in ('up', 'down')),
  created_at timestamptz not null default timezone('utc', now()),
  primary key (post_id, user_id)
);

create table public.post_bookmarks (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (post_id, user_id)
);

create index posts_level_created_at_idx on public.posts(level, created_at desc);
create index replies_post_created_at_idx on public.replies(post_id, created_at);
create index post_reactions_post_idx on public.post_reactions(post_id);
create index post_bookmarks_user_idx on public.post_bookmarks(user_id);

create or replace function public.is_verified_member()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid() is not null
    and exists (
      select 1 from auth.users
      where id = auth.uid() and email_confirmed_at is not null
    )
    and exists (
      select 1 from public.level_memberships where user_id = auth.uid()
    );
$$;

create or replace function public.create_profile_from_auth()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data->>'code_name', ''),
      nullif(new.raw_user_meta_data->>'display_name', ''),
      'Learner-' || upper(substr(replace(new.id::text, '-', ''), 1, 6))
    )
  )
  on conflict (id) do update set display_name = excluded.display_name;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.create_profile_from_auth();

alter table public.profiles enable row level security;
alter table public.level_memberships enable row level security;
alter table public.posts enable row level security;
alter table public.replies enable row level security;
alter table public.post_reactions enable row level security;
alter table public.post_bookmarks enable row level security;

create policy "Verified members can read profiles"
on public.profiles for select to authenticated
using (public.is_verified_member());

create policy "Members can read their own level membership"
on public.level_memberships for select to authenticated
using (user_id = auth.uid());

create policy "Members can create their own level membership"
on public.level_memberships for insert to authenticated
with check (user_id = auth.uid() and public.is_verified_member() = false);

create policy "Members can update their own level membership"
on public.level_memberships for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "Members can read posts in their level"
on public.posts for select to authenticated
using (public.is_verified_member() and exists (
  select 1 from public.level_memberships membership
  where membership.user_id = auth.uid() and membership.level = posts.level
));

create policy "Members can create posts in their level"
on public.posts for insert to authenticated
with check (author_id = auth.uid() and public.is_verified_member() and exists (
  select 1 from public.level_memberships membership
  where membership.user_id = auth.uid() and membership.level = posts.level
));

create policy "Members can read replies in their level"
on public.replies for select to authenticated
using (public.is_verified_member() and exists (
  select 1 from public.posts post
  join public.level_memberships membership on membership.level = post.level
  where post.id = replies.post_id and membership.user_id = auth.uid()
));

create policy "Members can reply in their level"
on public.replies for insert to authenticated
with check (author_id = auth.uid() and public.is_verified_member() and exists (
  select 1 from public.posts post
  join public.level_memberships membership on membership.level = post.level
  where post.id = replies.post_id and membership.user_id = auth.uid()
));

create policy "Members can read reactions in their level"
on public.post_reactions for select to authenticated
using (public.is_verified_member() and exists (
  select 1 from public.posts post
  join public.level_memberships membership on membership.level = post.level
  where post.id = post_reactions.post_id and membership.user_id = auth.uid()
));

create policy "Members can react in their level"
on public.post_reactions for insert to authenticated
with check (user_id = auth.uid() and public.is_verified_member() and exists (
  select 1 from public.posts post
  join public.level_memberships membership on membership.level = post.level
  where post.id = post_reactions.post_id and membership.user_id = auth.uid()
));

create policy "Members can remove their reactions"
on public.post_reactions for delete to authenticated
using (user_id = auth.uid());

create policy "Members can read their level bookmarks"
on public.post_bookmarks for select to authenticated
using (user_id = auth.uid());

create policy "Members can save posts in their level"
on public.post_bookmarks for insert to authenticated
with check (user_id = auth.uid() and public.is_verified_member() and exists (
  select 1 from public.posts post
  join public.level_memberships membership on membership.level = post.level
  where post.id = post_bookmarks.post_id and membership.user_id = auth.uid()
));

create policy "Members can remove their bookmarks"
on public.post_bookmarks for delete to authenticated
using (user_id = auth.uid());
